name: xp_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  readmore: ^2.2.0
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1

  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^2.24.2
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^11.6.5
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/onboarding_images/
    - assets/images/products/
    - assets/images/user/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
